imports:
  - php
tools:
  php_code_sniffer:
    filter:
      excluded-paths: [ spec/* ]
    config:
      standard: PSR2
  php_analyzer:
    filter:
      excluded-paths: [ spec/* ]
  php_sim:
    filter:
      excluded-paths: [ spec/* ]
build_failure_conditions:
    - 'issues.label("coding-style").exists'
filter:
  excluded_paths:
    - vendor/*
build:
  tests:
    override:
      -
        command: 'bin/phpspec run -f progress'
        coverage:
          file: 'build/coverage.xml'
          format: 'php-clover'